### ISSUE TITLE
show-config command errors when ansible.cfg file does not exist

### ISSUE THREAD

**Issue by haani-niyaz** [haani-niyaz/puppeteer#4]
```
$ puppeteer show-config

Traceback (most recent call last):
  File "/usr/local/bin/puppeteer", line 11, in <module>
    load_entry_point('puppeteer', 'console_scripts', 'puppeteer')()
  File "/Users/haani/batcave/scripts/python/puppeteer/puppeteer/__init__.py", line 13, in main
    cli.main()
  File "/Users/haani/batcave/scripts/python/puppeteer/puppeteer/cli.py", line 66, in main
    print(ansible_config_file.show())
  File "/Users/haani/batcave/scripts/python/puppeteer/puppeteer/fileops.py", line 31, in show
    self._validate_path()
  File "/Users/haani/batcave/scripts/python/puppeteer/puppeteer/fileops.py", line 23, in _validate_path
    "'{0}' does not exist.".format(self._infile))
puppeteer.fileops.YAMLFileError: 'ansible.cfg' does not exist.
```

**Comment by haani-niyaz** [comment]
Fixed and tagged on version `0.1.2`
